// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1dP0qdzPQYIglHSLTZ_72ss9XJz1JdA',
    appId: '1:890124867374:web:b0d4a3017dc9899edb4cbf',
    messagingSenderId: '890124867374',
    projectId: 'otp-verification-63633',
    authDomain: 'otp-verification-63633.firebaseapp.com',
    storageBucket: 'otp-verification-63633.firebasestorage.app',
    measurementId: 'G-XMM1BFQBX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcCbcAgoe2lQ-GMZ_z3BEb0elZ-3WqVck',
    appId: '1:890124867374:android:bcdd03be36609787db4cbf',
    messagingSenderId: '890124867374',
    projectId: 'otp-verification-63633',
    storageBucket: 'otp-verification-63633.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZvULOAFCe3tHobi8-Waeqf1Q5548XxAM',
    appId: '1:890124867374:ios:b22dafab039ebadfdb4cbf',
    messagingSenderId: '890124867374',
    projectId: 'otp-verification-63633',
    storageBucket: 'otp-verification-63633.firebasestorage.app',
    iosBundleId: 'com.example.raithanServiceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZvULOAFCe3tHobi8-Waeqf1Q5548XxAM',
    appId: '1:890124867374:ios:b22dafab039ebadfdb4cbf',
    messagingSenderId: '890124867374',
    projectId: 'otp-verification-63633',
    storageBucket: 'otp-verification-63633.firebasestorage.app',
    iosBundleId: 'com.example.raithanServiceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1dP0qdzPQYIglHSLTZ_72ss9XJz1JdA',
    appId: '1:890124867374:web:97ee36e0399139d1db4cbf',
    messagingSenderId: '890124867374',
    projectId: 'otp-verification-63633',
    authDomain: 'otp-verification-63633.firebaseapp.com',
    storageBucket: 'otp-verification-63633.firebasestorage.app',
    measurementId: 'G-980RC0LRRR',
  );
}
